spring:
  cloud:
    function:
      definition: processor
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        processor-in-0:
          destination: payment-request
          group: customer-payment-group
        processor-out-0:
          destination: payment-response
      kafka:
        binder:
          consumer-properties:
            "value.deserializer": org.springframework.kafka.support.serializer.JsonDeserializer
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "spring.json.trusted.packages": "*"
          producer-properties:
            "value.serializer": org.springframework.kafka.support.serializer.JsonSerializer
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer